# Source files
CFILES = main.c uart0driver.c log.c led.c keyboard.c display.c vs10xx.c \
remcon.c watchdog.c mmc.c spidrv.c mmcdrv.c fat.c flash.c rtc.c application.c


# Header files.
HFILES =        display.h keyboard.h led.h portio.h remcon.h log.h system.h \
settings.h inet.h platform.h version.h  update.h uart0driver.h typedefs.h \
vs10xx.h audio.h watchdog.h mmc.h flash.h spidrv.h command.h parse.h mmcdrv.h \
fat.h fatdrv.h flash.h rtc.h application.h types.h
